https://zhuanlan.zhihu.com/p/58416280

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 使用 read_parquet 加载parquet文件
import pandas as pd
import numpy as np
from pandas import read_parquet
data = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/label_test_source.parquet")
# data1 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/label_train_source.parquet")
# data2 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/label_train_target.parquet")
# data3 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/meta_song.parquet")
# data4 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/meta_song_composer.parquet")
# data5 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/meta_song_genre.parquet")
# data6 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/meta_song_lyricist.parquet")
# data7 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/meta_song_producer.parquet")
# data8 = read_parquet("/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/meta_song_titletext.parquet")

In [ ]:
df = data
print(df.count())
df.head(30)

session_id         2861280
song_id            2861280
unix_played_at     2861280
play_status        2861280
login_type         2861280
listening_order    2861280
dtype: int64

,session_id,song_id,unix_played_at,play_status,login_type,listening_order
0,598,43519381e8351d7c6afcc66bcc0a0636,1660177283,1,7,1
1,598,928e2e8e316f29efd986fa8d23429431,1660177503,1,7,2
2,598,5229859624d3b58c35646154cf366bf4,1660177582,1,7,3
3,598,49e50187f7a7f658623807780f499a15,1660177584,1,7,4
4,598,bc8b660fe4d4bfa0a13334beae0cb750,1660177587,1,7,5
5,598,743724b23a44300df22d204cf0f3702e,1660177588,1,7,6
6,598,12646130ef79f2d8fb7796e1586f58c4,1660177589,1,7,7
7,598,8a15b5b07ccef816853256013a6adc2d,1660177590,1,7,8
8,598,24d59f60232ddd07628179672ee007a1,1660177593,1,7,9
9,598,b75bcf271a082f0141c1ab0acfd86c43,1660177594,1,7,10
10,598,3b63b76baa890a14f1419eec8fd5ace2,1660177596,1,7,11
11,598,2f084b29da7c73d62e7f9087f9f2e90f,1660177597,1,7,12
12,598,5bf0eba45565652082863c40b0f59cd7,1660177599,1,7,13
13,598,bec020f45e95588e6106623571ea3dce,1660177599,1,7,14
14,598,49f7d2b20545dddaaf702b16bf8490f3,1660177603,1,7,15
15,598,a689c32ea9ae6bb905817aed73df6159,1660177604,1,7,16
16,598,5ecae3b68b3ad3cc2f6b4417e019d5db,1660177606,1,7,17
17,598,ea91150ebda0a80c473732c71f6a524f,1660264725,1,7,18
18,598,8cd8008ddffd9b2d12b6b7bf17474e9e,1660264726,1,7,19
19,598,e8bbc37dee09b8e548f0e2137dd1c2a5,1660265037,1,7,20
20,1039,3815658e81d42829193a7b2d186ae025,1660139717,1,7,1
21,1039,1c873169c3d6bf5729123a458ded41e2,1660140082,1,7,2
22,1039,e3d6da3aeb7dd8d3726a25e14d3e92a1,1660140306,1,7,3
23,1039,a5cc6f3cac3531d704f17eefbf5824a0,1660182479,1,7,4
24,1039,dd73de953fc9bd593fe13719dfd336a3,1660182560,1,7,5
25,1039,e23d3935f4e00f40a906815d46e317b3,1660182706,1,7,6
26,1039,247063e71d28e08010c4f4fa8301985a,1660182733,1,7,7
27,1039,cadf88145746fec4f6b97305e8781bc6,1660182775,1,7,8
28,1039,03a5ed92928509a3b87de77803c25468,1660182809,1,7,9
29,1039,5301b8e71ba93e326141954f3024b425,1660182837,1,7,10

In [ ]:
# Group by 'session_id' and 'song_id' and count occurrences
grouped_df = df.groupby(['session_id', 'song_id']).size().reset_index(name='count')

# Sort within each group by count in descending order
sorted_df = grouped_df.sort_values(['session_id', 'count'], ascending=[True, False])

# Extract the top five songs for each session
top_five_songs = sorted_df.groupby('session_id').head(5)

# Create a new column 'rank' indicating the rank of each song within each session
top_five_songs['rank'] = top_five_songs.groupby('session_id').cumcount() + 1

# Pivot the data to create a new DataFrame with 'session_id' and top five songs
df_pivoted = top_five_songs.pivot(index='session_id', columns='rank', values='song_id')

# Rename the columns to 'top1', 'top2', 'top3', 'top4', 'top5'
df_pivoted.columns = [f'top{i}' for i in range(1, 6)]

# Reset the index to include 'session_id' as a regular column
df_pivoted.reset_index(inplace=True)

<ipython-input-68-88c0ed968aef>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_five_songs['rank'] = top_five_songs.groupby('session_id').cumcount() + 1

In [ ]:
df_pivoted.head(10)

In [ ]:
# 假設 df_pivoted 是你的資料
# 使用 bfill（向後填補）來填補缺失值
df_pivoted[['top2', 'top3', 'top4', 'top5']] = df_pivoted[['top2', 'top3', 'top4', 'top5']].fillna(method='bfill', axis=1)

# 建立一個 fill_value 欄位，根據不同情況選擇 'top1'、'top2' 等欄位的值
fill_value = df_pivoted.apply(lambda row: row[['top1', 'top2', 'top3', 'top4', 'top5']].dropna().tolist() if any(row[['top1', 'top2', 'top3', 'top4', 'top5']].notna()) else [], axis=1)

# 使用 fill_value 來填補缺失值
df_pivoted[['top2', 'top3', 'top4', 'top5']] = df_pivoted[['top2', 'top3', 'top4', 'top5']].apply(lambda col: col.fillna(fill_value), axis=0)

In [ ]:
# replacing null values with the value from 'top1' column:
df_pivoted.fillna({'top2': df_pivoted['top1'], 'top3': df_pivoted['top1'], 'top4': df_pivoted['top1'], 'top5': df_pivoted['top1']}, inplace=True)

# Save the resulting DataFrame to a new CSV file
df_pivoted.to_csv('output.csv', index=False)
#print(df_pivoted)

In [ ]:
# prompt: 使用 DataFrame sample: 把sample存入csv檔案

df_pivoted.to_csv('/content/drive/MyDrive/Colab Notebooks/神經網路/dataset/resultbest.csv')